apiVersion: v1
kind: ServiceAccount
metadata:
  name: productreviewservice
  labels:
    app.kubernetes.io/name: productreviewservice
    app.kubernetes.io/part-of: opentelemetry-demo
    app.kubernetes.io/component: service
