apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-reviews
  labels:
    app.kubernetes.io/name: product-reviews
    app.kubernetes.io/part-of: opentelemetry-demo
    app.kubernetes.io/component: backend
