# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ServiceAccount
metadata:
  name: email-service
  namespace: otel-demo
  labels:
    app.kubernetes.io/name: email
    app.kubernetes.io/part-of: opentelemetry-demo
    app.kubernetes.io/version: "latest"
