apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opentelemetry-demo-prometheus
  labels:
    app.kubernetes.io/name: opentelemetry-demo
    app.kubernetes.io/component: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
