apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: opentelemetry-demo
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: opentelemetry-demo
spec:
  type: ClusterIP
  ports:
    - name: plaintext
      port: 9092
      targetPort: 9092
      protocol: TCP
    # Uncomment below to enable TLS port
    # - name: tls
    #   port: 9093
    #   targetPort: 9093
    #   protocol: TCP
  selector:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: opentelemetry-demo
