apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
  labels:
    app.kubernetes.io/name: postgresql
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
