apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-storage
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: opentelemetry-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
