apiVersion: v1
kind: ServiceAccount
metadata:
  name: opentelemetry-demo-prometheus
  namespace: default
  labels:
    app.kubernetes.io/name: opentelemetry-demo
    app.kubernetes.io/component: prometheus
