# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ServiceAccount
metadata:
  name: adservice
  labels:
    app.kubernetes.io/name: adservice
    app.kubernetes.io/part-of: opentelemetry-demo
    app.kubernetes.io/version: "latest"
