# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: shippingservice
  labels:
    app.kubernetes.io/name: shippingservice
    app.kubernetes.io/part-of: opentelemetry-demo
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: grpc
      targetPort: grpc
  selector:
    app.kubernetes.io/name: shippingservice
