apiVersion: v1
kind: Service
metadata:
  name: currency-service
  labels:
    app.kubernetes.io/name: currency-service
    app.kubernetes.io/part-of: opentelemetry-demo
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 7000
      targetPort: 7000
      protocol: TCP
    - name: health
      port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app.kubernetes.io/name: currency-service
