jaeger:
  pvc:
    storageClassName: ""
    storageSize: "10Gi"
    accessModes:
      - ReadWriteOnce
  retention:
    ttl: "7d"
grafana:
  persistence:
    enabled: true
    storageClassName: ""
    size: 10Gi
    existingClaim: "grafana-storage"
