apiVersion: v1
kind: ServiceAccount
metadata:
  name: quote-service
  namespace: opentelemetry-demo
  labels:
    app.kubernetes.io/name: quote-service
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: opentelemetry-demo
