# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-catalog
  labels:
    app.kubernetes.io/name: product-catalog
    app.kubernetes.io/part-of: opentelemetry-demo
automountServiceAccountToken: true
