apiVersion: v1
kind: ServiceAccount
metadata:
  name: opentelemetry-demo-productcatalogservice
  namespace: opentelemetry-demo
  labels:
    app.kubernetes.io/name: productcatalogservice
    app.kubernetes.io/part-of: opentelemetry-demo
    app.kubernetes.io/component: service
automountServiceAccountToken: true
