apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-config
  namespace: opentelemetry-demo
  labels:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/version: "2.14.1"
data:
  jaeger.yaml: |
    badger:
      ephemeral: false
      directory-key: /badger/key
      directory-value: /badger/data
    retention:
      go:
        traces:
          ttl: 7d
    service:
      telemetry:
        health-check-http:
          host-port: 0.0.0.0:14269
    tls:
      enabled: ${JAEGER_TLS_ENABLED:false}
      cert-file: ${JAEGER_TLS_CERT_PATH:}
      key-file: ${JAEGER_TLS_KEY_PATH:}
      client-ca-file: ${JAEGER_TLS_CA_CERT_PATH:}
      min-version: "1.2"
