apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jaeger-storage
  namespace: opentelemetry-demo
  labels:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/instance: jaeger
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
