apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: opentelemetry-demo
  labels:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/version: "2.14.1"
spec:
  type: ClusterIP
  ports:
    - name: ui
      port: 16686
      targetPort: ui
      protocol: TCP
    - name: grpc-model
      port: 14250
      targetPort: grpc-model
      protocol: TCP
    - name: http-thrift
      port: 14268
      targetPort: http-thrift
      protocol: TCP
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
      protocol: TCP
    - name: admin-health
      port: 14269
      targetPort: admin-health
      protocol: TCP
  selector:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/instance: jaeger
