apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: opentelemetry-demo
  labels:
    app.kubernetes.io/part-of: opentelemetry-demo
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: database
    app.kubernetes.io/version: "15"
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: database
